### ISSUE TITLE
deno runtime support

### ISSUE THREAD

**Issue by adminy** [alysonhower/tauri2-svelte5-boilerplate#1]
I was looking at this,

svelte 5 - my favourite framework!
Tauri 2 - the best in class, its what I'd go with making apps.
DaisyUI - my favourite component lib.

I like bun also, but if I can cut out tsconfig and a bunch of packages and import typescripted typed packages that have proper intelisense. I'd like it to be there instead of bun. no hate on bun, just think deno does cut out a few things. gives them for free.

**Comment by alysonhower** [comment]
Thank you for your suggestion.

I confess that I didn't really know Deno until you made me this suggestion. This tool is really very useful and I confess that I would love to switch to Deno.

I tryed to scaffold a Deno Svelte project but unfortunately I didn't fully achieved it with success. The problem is that apparently Deno and Svelte don't communicate well even with the compatibility with the Node that Deno 2 brought recently. As you can see: I created a project using the command ```deno run -A npm:create-vite-extra``` (choose deno-svelte) and the project was even created, but got problems right away as some warnings appeared when running ```deno task dev```.

I quickly tried to troubleshoot it just to make sure it's not a small one-off problem and found nothing, but I found this comment from Rich himself: https://github.com/sveltejs/svelte/pull/13204#issuecomment-2353671231

Apparently Rich doesn't have good impressions of Deno yet. Probably he didn't have time to test the new version or there are deeper problems, I don't know. But for that comment I think I'll have some trouble setting it.

However if you could help me creating a proper Sveltekit project as you have a deeper understanding of Deno related ecossystems, I would love to create a Deno branch.

**Comment by adminy** [comment]
Yeah, I excitedly thought it works well with anything. I think partially they want to compete with vite, which is why vite doesn't have proper support, given itself is using swc to compile js. I recently tried a surreal project with deno and vite and svelte, even though they claim to be fully node compatible, it seems not to be the case as I was getting some scary go log traces. In some libraries I've seen where its hardcoded runtimes conditionals. same story with package managers. I can see were Rich is coming from. I was hopeful that it will reduce the amount of code to set up a project. I'm still currious, because the likes of svelte are going to try and build with vite, which sounds like something that could become part of the standard, but then libraries like svelte have to be realistic, they cannot design this with too many things to support, I'm sure its complex enough as is. Vite has gained mass while deno is fairly new idea. Deno doesn't support custom parsers like vite does yet.
